services:
  vllm:
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    ipc: host
    runtime: nvidia
    shm_size: '32gb'
    environment:
      - VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/vllm:/root/.cache/vllm
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 600s
