include:
  - ../../docker-compose.common.yml

services:
  vllm:
    image: vllm/vllm-openai:gemma4-cu130-fixed
    container_name: gemma4-26b-a4b-it
    command:
      - "cyankiwi/gemma-4-26B-A4B-it-AWQ-4bit"
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--gpu-memory-utilization=0.90"
      - "--reasoning-parser=gemma4"
      - "--enable-auto-tool-choice"
      - "--enable-prefix-caching"
      - "--tool-call-parser=gemma4"
      - "--enable-prefix-caching"
      - "--enable-chunked-prefill"
      - "--max-num-seqs=2"
      - "--max-num-batched-tokens=8192"
