include:
  - ../../docker-compose.common.yml

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: qwen3.8-27b-nvfp4
    command:
      - "gittensor-model-hub/Qwen3.8-27B-NVFP4-RTX5090"
      - "--quantization=modelopt"
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--max-model-len=200000"
      - "--gpu-memory-utilization=0.93"
      - "--max-num-seqs=2"
      - "--attention-backend=flashinfer"
      - "--max-num-batched-tokens=16384"
      - "--kv-cache-dtype=fp8"
      - "--reasoning-parser=qwen3"
      - "--enable-auto-tool-choice"
      - "--enable-prefix-caching"
      - "--enable-chunked-prefill"
      - "--tool-call-parser=qwen3_xml"
      - --speculative-config
      - '{"method":"mtp","num_speculative_tokens":3}'
      - "--safetensors-load-strategy=prefetch"
