include:
  - ../../docker-compose.common.yml

services:
  vllm:
    image: vllm/vllm-openai:cu130-nightly
    container_name: qwen3.5-27b-awq
    command:
      - "QuantTrio/Qwen3.5-27B-AWQ"
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--reasoning-parser=qwen3"
      - "--enable-auto-tool-choice"
      - "--enable-prefix-caching"
      - "--tool-call-parser=qwen3_coder"
      - "--language-model-only"
