include:
  - ../../docker-compose.common.yml

services:
  vllm:
    image: vllm/vllm-openai:cu130-nightly
    container_name: qwen3.5-27b-nvfp4
    command:
      - "apolo13x/Qwen3.5-27B-NVFP4"
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--max-model-len=234567"
      - "--gpu-memory-utilization=0.89"
      - "--max-num-seqs=4"
      - "--max-num-batched-tokens=4096"
      - "--kv-cache-dtype=fp8"
      - "--reasoning-parser=qwen3"
      - "--enable-auto-tool-choice"
      - "--enable-prefix-caching"
      - "--tool-call-parser=qwen3_coder"
      - "--language-model-only"
